export enum ActionTypes {
    //calendar
    SET_MONTH = 'SET_MONTH',
    //add dialog
    SET_ADD_SCHEDULE_DIALOG = "SET_ADD_SCHEDULE_DIALOG",
    OPEN_ADD_SCHEDULE_DIALOG = "OPEN_ADD_SCHEDULE_DIALOG",
    CLOSE_ADD_SCHEDULE_DIALOG = "CLOSE_ADD_SCHEDULE_DIALOG",
    //schedules
    ADD_SCHEDULES = "ADD_SCHEDULES",
    DELETE_SCHEDULE = "DELETE_SCHEDULE",
    FETCH_SCHEDULES = "FETCH_SCHEDULES",
    SET_SCHEDULES_LOADING = "SET_SCHEDULES_LOADING",
    //show dialog
    SET_SHOW_SCHEDULE_DIALOG = "SET_SHOW_SCHEDULE_DIALOG",
    OPEN_SHOW_SCHEDULE_DIALOG = "OPEN_SHOW_SCHEDULE_DIALOG",
    CLOSE_SHOW_SCHEDULE_DIALOG = "CLOSE_SHOW_SCHEDULE_DIALOG",
}
